-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.candidates
(
    first_name character varying(15),
    last_name character varying(15),
    id integer NOT NULL,
    birth_year integer,
    national_id character varying(11),
    PRIMARY KEY (id)
);

CREATE TABLE public.cities
(
    id integer NOT NULL,
    city_name character varying(20),
    PRIMARY KEY (id)
);

CREATE TABLE public.colleges
(
    id integer NOT NULL,
    college_name character varying(25),
    departmant character varying(20),
    graduated_date date,
    starting_date date,
    candidates_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.cover_letter
(
    id integer NOT NULL,
    description character varying(400),
    candidates_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.employees
(
    first_name character varying(15),
    last_name character varying(20),
    id integer NOT NULL,
    department_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.employers
(
    company_name character varying(25),
    confirmation boolean,
    phone_number character varying(14),
    website character varying(25),
    id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public.experiences
(
    id integer NOT NULL,
    end_date date,
    starting_date date,
    workplace character varying(25),
    candidates_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.images
(
    id integer NOT NULL,
    created_date date,
    url character varying(400),
    user_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.job_positions
(
    id integer NOT NULL,
    title character varying(25),
    name character varying(25),
    PRIMARY KEY (id)
);

CREATE TABLE public.job_posts
(
    id integer NOT NULL,
    end_of_job_date timestamp without time zone,
    job_description character varying(255),
    number_of_job_position character varying(255),
    max_salary character varying(10),
    min_salary character varying(10),
    post_date date,
    status boolean,
    city_id integer,
    employer_id integer,
    position_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.languages
(
    id integer NOT NULL,
    langauge character varying(20),
    level integer,
    candidates_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.skills
(
    id integer NOT NULL,
    technology_name character varying(20),
    candidates_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.social_media_links
(
    id integer NOT NULL,
    link character varying(255),
    name character varying(25),
    candidates_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.users
(
    id integer NOT NULL,
    password character varying(10),
    email character varying(25),
    PRIMARY KEY (id)
);

ALTER TABLE public.candidates
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.colleges
    ADD FOREIGN KEY (candidates_id)
    REFERENCES public.candidates (id)
    NOT VALID;


ALTER TABLE public.cover_letter
    ADD FOREIGN KEY (candidates_id)
    REFERENCES public.candidates (id)
    NOT VALID;


ALTER TABLE public.employees
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.experiences
    ADD FOREIGN KEY (candidates_id)
    REFERENCES public.candidates (id)
    NOT VALID;


ALTER TABLE public.images
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.job_posts
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.employers (id)
    NOT VALID;


ALTER TABLE public.job_posts
    ADD FOREIGN KEY (position_id)
    REFERENCES public.job_positions (id)
    NOT VALID;


ALTER TABLE public.job_posts
    ADD FOREIGN KEY (city_id)
    REFERENCES public.cities (id)
    NOT VALID;


ALTER TABLE public.languages
    ADD FOREIGN KEY (candidates_id)
    REFERENCES public.candidates (id)
    NOT VALID;


ALTER TABLE public.skills
    ADD FOREIGN KEY (candidates_id)
    REFERENCES public.candidates (id)
    NOT VALID;


ALTER TABLE public.social_media_links
    ADD FOREIGN KEY (candidates_id)
    REFERENCES public.candidates (id)
    NOT VALID;

END;