-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.candidates
(
    first_name character varying(20),
    last_name character varying(20),
    id integer NOT NULL,
    birth_year integer,
    national_id character varying(11),
    user_id integer NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.cities
(
    id integer NOT NULL,
    city_name character varying(20),
    PRIMARY KEY (id)
);

CREATE TABLE public.employees
(
    first_name character varying(20),
    last_name character varying(20),
    id integer NOT NULL,
    user_id integer NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.employers
(
    company_name character varying(20),
    confirmation boolean,
    phone_number character varying(15),
    website character varying(50),
    id integer NOT NULL,
    user_id integer NOT NULL,
    PRIMARY KEY (user_id)
);

CREATE TABLE public.job_positions
(
    id integer NOT NULL,
    title character varying(25),
    name character varying(25),
    PRIMARY KEY (id)
);

CREATE TABLE public.job_posts
(
    id integer NOT NULL,
    end_of_job_date date,
    job_description character varying(255),
    number_of_job_position character varying(255),
    max_salary character varying(255),
    min_salary character varying(255),
    post_date date,
    status boolean,
    city_id integer,
    employer_id integer,
    position_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE public.users
(
    id integer NOT NULL,
    password character varying(20),
    email character varying(20),
    PRIMARY KEY (id)
);

ALTER TABLE public.candidates
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employees
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.employers
    ADD FOREIGN KEY (id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.job_posts
    ADD FOREIGN KEY (employer_id)
    REFERENCES public.employers (id)
    NOT VALID;


ALTER TABLE public.job_posts
    ADD FOREIGN KEY (position_id)
    REFERENCES public.job_positions (id)
    NOT VALID;


ALTER TABLE public.job_posts
    ADD FOREIGN KEY (city_id)
    REFERENCES public.cities (id)
    NOT VALID;

END;